#! /bin/bash

PARAMETERS="PORT NODE USERNAME PASSWORD LISTENER ADAPTER_NORTHBOUND_IP_ADDRESS ADAPTER_SOUTHBOUND_IP_ADDRESS"

DEFAULT_PORT="2222"
DEFAULT_NODE="192.168.100.1"
DEFAULT_USERNAME="netsim"
DEFAULT_PASSWORD="netsim"
DEFAULT_LISTENER="com.ericsson.ranexplorer.yangecimadapter.netconf.rpc.handler.config.listener.AdapterListener"
DEFAULT_ADAPTER_NORTHBOUND_IP_ADDRESS="0.0.0.0"
DEFAULT_ADAPTER_SOUTHBOUND_IP_ADDRESS="0.0.0.0"

[ -z "$PORT" ] && PORT=$DEFAULT_PORT
[ -z "$NODE" ] && NODE=$DEFAULT_NODE
[ -z "$USERNAME" ] && USERNAME=$DEFAULT_USERNAME
[ -z "$PASSWORD" ] && PASSWORD=$DEFAULT_PASSWORD
[ -z "$LISTENER" ] && LISTENER=$DEFAULT_LISTENER
[ -z "$ADAPTER_NORTHBOUND_IP_ADDRESS" ] && ADAPTER_NORTHBOUND_IP_ADDRESS=$DEFAULT_ADAPTER_NORTHBOUND_IP_ADDRESS
[ -z "$ADAPTER_SOUTHBOUND_IP_ADDRESS" ] && ADAPTER_SOUTHBOUND_IP_ADDRESS=$DEFAULT_ADAPTER_SOUTHBOUND_IP_ADDRESS

for PARAM in $PARAMETERS; do
  [ -z "$PARAM_INDEX" ] && PARAM_INDEX=0
  DEFAULT_VALUE_PARAM="DEFAULT_$PARAM"
  PARAM_VALUE=${!PARAM}
  
  [ -z "${PARAM_VALUE}" ] && PARAM_VALUE=${!DEFAULT_VALUE_PARAM}

  PARAM_ENTRY="$PARAM=${PARAM_VALUE}"
  PARAMETERS_ARRAY[$PARAM_INDEX]=$PARAM_ENTRY
  
  echo "$PARAM value is ${PARAM_VALUE}"
  
  PARAM_INDEX=$(($PARAM_INDEX+1))
done
 echo ${PARAMETERS_ARRAY[*]}

java -Dlogback.configurationFile=logback.xml -jar ${SERVER_PATH}adapter-server-${project.version}.jar ssh --port $PORT -n $NODE -u $USERNAME -p $PASSWORD -a $ADAPTER_NORTHBOUND_IP_ADDRESS -b $ADAPTER_SOUTHBOUND_IP_ADDRESS -c $LISTENER


